#!/bin/bash
set -euo pipefail


# ==================================================================
# VARIABLES
# ==================================================================

homebrew_packages=(
  "bash"
  "git"
  "mas"
  "n"
  "node"
  "vim"
  "yarn"
  "zsh"
  "openssl"
  "rethinkdb"
  "mongodb"
)

ruby_gems=(
  "travis"
)

fonts=(
  "font-fira-code"
  "font-fira-mono"
  "font-quicksand"
)

homebrew_cask_apps=(
  "lastpass"
  "google-chrome"
  "google-drive"
  "google-photos-backup"
  "hyper"
  "iterm2"
  "rescuetime"
  "flux"
  "visual-studio-code-insiders"
  "marshallofsound-google-play-music-player"
)

mac_app_store_apps=(
  "455970963" # Disk Doctor
  "408981434" # iMovie
  "803453959" # Slack
  "413857545" # Divvy
  "425424353" # The Unarchiver
  "451444120" # Memory Clean
)

vscode_packages=(
  "streetsidesoftware.code-spell-checker"
  "ms-vsliveshare.vsliveshare"
  "wakatime.vscode-wakatime"
  "rebornix.nova"
  "whtouche.vscode-js-console-utils"
  "wix.vscode-import-cost"
  "waderyan.gitblame"
  "dbaeumer.vscode-eslint"
)


# ==================================================================
# SHELL
# ==================================================================


# ==================================================================
# MACOS
# ==================================================================

# KEYBOARD
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# HIDDEN FILES
echo "Configuring hidden files to show"
defaults write com.apple.finder AppleShowAllFiles YES
killall Finder

# SCREENSHOTS
echo "Configuring screenshots to save in Downloads"
defaults write com.apple.screencapture location ~/Downloads
killall SystemUIServer

# CHROME
defaults write com.google.chrome IncognitoModeAvailability -integer 1


# ==================================================================
# PACKAGES
# ==================================================================

# HOMEBREW
echo "Installing Homebrew packages"
for homebrew_package in "${homebrew_packages[@]}"; do
  brew install "$homebrew_package"
done

# RUBY
echo "Installing Ruby gems"
for ruby_gem in "${ruby_gems[@]}"; do
  gem install "$ruby_gem"
done

# CONFIG
echo "Upgrade to latest Node"
n latest


# ==================================================================
# DOTFILES
# ==================================================================

echo "Symlinking dotfiles"
for file in $(find "$HOME/drive/settings/dotfiles" -depth 1 -exec basename {} \;); do
  ln -s "$HOME/drive/settings/dotfiles/$file" "$HOME/$file"
done


# ==================================================================
# VIM PLUGINS & FOLDERS
# ==================================================================

echo "Installing Vim Plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Installing Vim plugins"
vim +PlugInstall +qall

echo "Making UltiSnips symlinks"
mkdir ~/.vim/UltiSnips/
ln -s ~/drive/settings/syncfiles/UltiSnips/all.snippets ~/.vim/UltiSnips/

echo "Making temp file directories"
mkdir ~/.vim/{backup_files,swap_files,undo_files}


# ==================================================================
# FONTS
# ==================================================================
echo "Installing Google Fonts"
curl https://raw.githubusercontent.com/qrpike/Web-Font-Load/master/install.sh | sh

echo "Adding Homebrew fonts tap"
brew tap caskroom/fonts
echo "Installing Homebrew fonts"
for font in "${fonts[@]}"; do
  brew cask install "$font"
done


# ==================================================================
# GUI APPS
# Needed for heavy creation, background processes, or OS integration
# ==================================================================

echo "Installing Homebrew cask apps"
for homebrew_cask_app in "${homebrew_cask_apps[@]}"; do
  brew cask install "$homebrew_cask_app"
done

echo "Installing VSCode Packages"
for vscode_package in "${vscode_packages[@]}"; do
  code --install-extension  install "$vscode_package"
done

echo "Installing VSCode-Insiders Packages"
for vscode_package in "${vscode_packages[@]}"; do
  code-insiders --install-extension  install "$vscode_package"
done

echo "Installing Mac App Store apps"
for mac_app_store_app in "${mac_app_store_apps[@]}"; do
  mas install "$mac_app_store_app"
done


# ==================================================================
# MANUAL SETUP
# ==================================================================

# NPM
echo "Log in to npm registry with package manager"
yarn login

# TRAVIS
echo "Log in to Travis CI"
travis login


# ==================================================================

echo "Done"
